// <copyright file="GlobalSuppressions.cs" company="BCKFreightTMS">
// Copyright (c) BCKFreightTMS. All Rights Reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.NoVATTaxCoutryNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.ActionNotFinishedReasons")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "<Pending>", Scope = "namespace", Target = "~N:BCKFreightTMS.Common")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.AdministratorRoleName")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.BGOrderNumberFormat")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.DueDaysValues")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.ExchangeRateUrl")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.Index")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.InvoiceOutNumberFormat")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.JsonDataPath")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.MinOrderMargin")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.NonBGOrderNumberFormat")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.PdfMimeType")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.RegistryAgencyUrl")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.RegistryAgencyUrlSearch")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.SmallOrderMaxAmount")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.SmallOrderMinMargin")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.SystemEmail")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.GlobalConstants.SystemName")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.ActionTypeNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.CurrencyCodes")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.InvoiceStatusNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.LoadingBodyNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.NoVATTaxCoutryNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.OrderStatusNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.PaymentMethods")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.PersonRoleNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.RoleNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.TaxCountryNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VATReasons")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VATReasonsIn")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VATReasonsOut")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VehicleTypeNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.GlobalConstants")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.ActionTypeNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.CurrencyCodes")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.InvoiceStatusNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.LoadingBodyNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.OrderStatusNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.PaymentMethods")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.PersonRoleNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.RoleNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.TaxCountryNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VATReasons")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VATReasonsIn")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VATReasonsOut")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.VehicleTypeNames")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.NotArr")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AccNoPart")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AccPart")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AtAdr1")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AtAdr2")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AtAdr3")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AtAdr4")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.AtAdrToday")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.OffTime")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.Police")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~F:BCKFreightTMS.Common.AccountingTypes.TrPolice")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.AccountingTypes")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.CreditAccountingTypes")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.DebitAccountingTypes")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.CreditAccountingTypes")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "<Pending>", Scope = "type", Target = "~T:BCKFreightTMS.Common.Enums.DebitAccountingTypes")]
