// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.ExternalLoginModel.OnGetAsync~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.ForgotPasswordModel.OnPostAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.LoginModel.OnGetAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.LoginWith2faModel.OnGetAsync(System.Boolean,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel.OnGetAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.Manage.ChangePasswordModel.OnGetAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.Manage.EmailModel.LoadAsync(BCKFreightTMS.Data.Models.ApplicationUser)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.Manage.EnableAuthenticatorModel.OnGetAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.Manage.IndexModel.LoadAsync(BCKFreightTMS.Data.Models.ApplicationUser)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.Manage.SetPasswordModel.OnGetAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.RegisterModel.OnGetAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:BCKFreightTMS.Web.Areas.Identity.Pages.Account.ResetPasswordModel.OnGet(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~P:BCKFreightTMS.Web.Areas.Identity.Pages.Account.Manage.DeletePersonalDataModel.RequirePassword")]
